# Lasso & Ridge regression

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.metrics import r2_score

In [2]:
data = pd.read_csv(r'D:\Full Stack Data Science With Gen AI & Agentic AI Notes\Notes\May\12 May\Lasso, ridge & elastic net\Task - Lasso & ridge\Car mpg.csv')

In [3]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   mpg       398 non-null    float64
 1   cyl       398 non-null    int64
 2   disp      398 non-null    float64
 3   hp        398 non-null    str
 4   wt        398 non-null    int64
 5   acc       398 non-null    float64
 6   yr        398 non-null    int64
 7   origin    398 non-null    int64
 8   car_type  398 non-null    int64
 9   car_name  398 non-null    str
dtypes: float64(3), int64(5), str(2)
memory usage: 38.4 KB

In [4]:
data.head()

,mpg,cyl,disp,hp,wt,acc,yr,origin,car_type,car_name
0,18.0,8,307.0,130,3504,12.0,70,1,0,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,0,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,0,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,0,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,0,ford torino

In [5]:
data = data.drop(['car_name'], axis = 1)
data['origin'] = data['origin'].replace({1:'america', 2:'europe', 3:'asia'})
data = pd.get_dummies(data, columns = ['origin'], dtype = int)

In [6]:
data.head()

,mpg,cyl,disp,hp,wt,acc,yr,car_type,origin_america,origin_asia,origin_europe
0,18.0,8,307.0,130,3504,12.0,70,0,1,0,0
1,15.0,8,350.0,165,3693,11.5,70,0,1,0,0
2,18.0,8,318.0,150,3436,11.0,70,0,1,0,0
3,16.0,8,304.0,150,3433,12.0,70,0,1,0,0
4,17.0,8,302.0,140,3449,10.5,70,0,1,0,0

In [7]:
data = data.replace('?', np.nan)
data = data.apply(pd.to_numeric)
data = data.apply(lambda x : x.fillna(x.median()) if x.dtype != 'object' else x, axis = 0)

In [8]:
data.head()

,mpg,cyl,disp,hp,wt,acc,yr,car_type,origin_america,origin_asia,origin_europe
0,18.0,8,307.0,130.0,3504,12.0,70,0,1,0,0
1,15.0,8,350.0,165.0,3693,11.5,70,0,1,0,0
2,18.0,8,318.0,150.0,3436,11.0,70,0,1,0,0
3,16.0,8,304.0,150.0,3433,12.0,70,0,1,0,0
4,17.0,8,302.0,140.0,3449,10.5,70,0,1,0,0

In [9]:
x = data.drop(['mpg'], axis = 1)
y = data[['mpg']]

In [10]:
x.head()

,cyl,disp,hp,wt,acc,yr,car_type,origin_america,origin_asia,origin_europe
0,8,307.0,130.0,3504,12.0,70,0,1,0,0
1,8,350.0,165.0,3693,11.5,70,0,1,0,0
2,8,318.0,150.0,3436,11.0,70,0,1,0,0
3,8,304.0,150.0,3433,12.0,70,0,1,0,0
4,8,302.0,140.0,3449,10.5,70,0,1,0,0

In [11]:
 y.head()

    mpg
0  18.0
1  15.0
2  18.0
3  16.0
4  17.0

In [12]:
x_s = preprocessing.scale(x)
x_s = pd.DataFrame(x_s, columns = x.columns)

In [13]:
x_s

,cyl,disp,hp,wt,acc,yr,car_type,origin_america,origin_asia,origin_europe
0,1.498191,1.090604,0.673118,0.630870,-1.295498,-1.627426,-1.062235,0.773559,-0.497643,-0.461968
1,1.498191,1.503514,1.589958,0.854333,-1.477038,-1.627426,-1.062235,0.773559,-0.497643,-0.461968
2,1.498191,1.196232,1.197027,0.550470,-1.658577,-1.627426,-1.062235,0.773559,-0.497643,-0.461968
3,1.498191,1.061796,1.197027,0.546923,-1.295498,-1.627426,-1.062235,0.773559,-0.497643,-0.461968
4,1.498191,1.042591,0.935072,0.565841,-1.840117,-1.627426,-1.062235,0.773559,-0.497643,-0.461968
...,...,...,...,...,...,...,...,...,...,...
393,-0.856321,-0.513026,-0.479482,-0.213324,0.011586,1.621983,0.941412,0.773559,-0.497643,-0.461968
394,-0.856321,-0.925936,-1.370127,-0.993671,3.279296,1.621983,0.941412,-1.292726,-0.497643,2.164651
395,-0.856321,-0.561039,-0.531873,-0.798585,-1.440730,1.621983,0.941412,0.773559,-0.497643,-0.461968
396,-0.856321,-0.705077,-0.662850,-0.408411,1.100822,1.621983,0.941412,0.773559,-0.497643,-0.461968
397,-0.856321,-0.714680,-0.584264,-0.296088,1.391285,1.621983,0.941412,0.773559,-0.497643,-0.461968

In [14]:
y_s = preprocessing.scale(y)
y_s = pd.DataFrame(y_s, columns = y.columns)

In [15]:
y_s

          mpg
0   -0.706439
1   -1.090751
2   -0.706439
3   -0.962647
4   -0.834543
..        ...
393  0.446497
394  2.624265
395  1.087017
396  0.574601
397  0.958913

[398 rows x 1 columns]

In [16]:
x_train, x_test, y_train, y_test = train_test_split(x_s, y_s, test_size = 0.3, random_state = 0)

In [17]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(278, 10)
(120, 10)
(278, 1)
(120, 1)

In [18]:
len(data)

398

In [19]:
data.columns

Index(['mpg', 'cyl', 'disp', 'hp', 'wt', 'acc', 'yr', 'car_type',
       'origin_america', 'origin_asia', 'origin_europe'],
      dtype='str')

In [20]:
regression_model = LinearRegression()
regression_model.fit(x_train, y_train)

for idx, col_name in enumerate(x_train.columns):
    print('The coef for {} is {}'.format(col_name, regression_model.coef_[0][idx]))

intercept = regression_model.intercept_[0]
print('The intercept is {}'.format(intercept))

The coef for cyl is 0.2474447975894671
The coef for disp is 0.28838215446098686
The coef for hp is -0.18990342687152878
The coef for wt is -0.673222906511177
The coef for acc is 0.0675450154068818
The coef for yr is 0.34463640721172734
The coef for car_type is 0.31491491540037686
The coef for origin_america is -0.07682943694882902
The coef for origin_asia is 0.0633604889661997
The coef for origin_europe is 0.031283357351475284
The intercept is -0.019500467624017432

In [21]:
# Ridge model

ridge_model = Ridge(alpha = 0.4)
ridge_model.fit(x_train, y_train)
print('Ridge model coef: {}'.format(ridge_model.coef_))

Ridge model coef: [ 0.2431613   0.27536624 -0.18977371 -0.66177905  0.06534252  0.34374093
  0.31063723 -0.07629922  0.06332619  0.03064529]

In [22]:
# Lasso model

lasso_model = Lasso(alpha = 0.1)
lasso_model.fit(x_train, y_train)
print('Lasso model coef:{}'.format(lasso_model.coef_))

Lasso model coef:[-0.         -0.         -0.06203044 -0.48363379  0.          0.27163751
  0.09620861 -0.03490256  0.          0.        ]

In [23]:
# Model score - R-squared

# Simple linear model
print(regression_model.score(x_train, y_train))
print(regression_model.score(x_test, y_test))
print('******************')

# Ridge
print(ridge_model.score(x_train, y_train))
print(ridge_model.score(x_test, y_test))
print('******************')

# Lasso
print(lasso_model.score(x_train, y_train))
print(lasso_model.score(x_test, y_test))

0.836163800114943
0.8439452810748138
******************
0.8361431007135053
0.8437289477126599
******************
0.7994535676270829
0.81026554865651